version: '2.3'

services:
  predict-server1:
    container_name: predict-container1
    image: predict-image
    build:
      context: "predict/"
      dockerfile: Dockerfile_dev
    volumes:
      - ${PWD}/predict:/predict
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5010:5010"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      GRAB_CUT_ITERS: "1"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5010 -w 1 -k uvicorn.workers.UvicornWorker --reload"

  predict-server2:
    container_name: predict-container2
    image: predict-image
    build:
      context: "predict/"
      dockerfile: Dockerfile_dev
    volumes:
      - ${PWD}/predict:/predict
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5011:5011"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      GRAB_CUT_ITERS: "10"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5011 -w 1 -k uvicorn.workers.UvicornWorker --reload"

  proxy-server1:
    container_name: proxy-container1
    image: proxy-image
    build:
      context: "proxy/"
      dockerfile: Dockerfile_dev
    volumes:
      - ${PWD}/proxy:/proxy
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - predict-server1
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PREDICT_SERVER_URL: "http://predict-container1:5010"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5000 -w 1 -k uvicorn.workers.UvicornWorker --reload"

  proxy-server2:
    container_name: proxy-container2
    image: proxy-image
    build:
      context: "proxy/"
      dockerfile: Dockerfile_dev
    volumes:
      - ${PWD}/proxy:/proxy
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5001:5001"
    tty: true
    depends_on:
      - predict-server2
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PREDICT_SERVER_URL: "http://predict-container2:5011"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5001 -w 1 -k uvicorn.workers.UvicornWorker --reload"
