# 変数値の置換
substitutions:
  _JOB_IMAGE_NAME: fast-api-rate-limit-image-gke

steps:
  #-----------------------------------
  # 推論サーバー
  #-----------------------------------
  # キャッシュされたイメージを Container Registry から pull
  # 初めてイメージをビルドする際は docker pull で pull できる既存のイメージがないため、entrypoint を bash に設定し、コマンドの実行で返されるエラーを無視できるようにしている
  - name: 'gcr.io/cloud-builders/docker'
    id: docker pull job
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_JOB_IMAGE_NAME}:latest || exit 0']

  # Container Registry 上で docker image 作成 
  - name: 'gcr.io/cloud-builders/docker'
    id: docker build job
    args: [
      'build', 
      '-t', 'gcr.io/${PROJECT_ID}/${_JOB_IMAGE_NAME}:latest', 
      '--cache-from', 'gcr.io/${PROJECT_ID}/${_JOB_IMAGE_NAME}:latest',
      '-f', 'api/Dockerfile',
      '.'
    ]

  # Container Registry 上に docker image を登録
  - name: 'gcr.io/cloud-builders/docker'
    id: docker push job
    args: ['push', 'gcr.io/${PROJECT_ID}/${_JOB_IMAGE_NAME}:latest']

images: ['gcr.io/${PROJECT_ID}/${_JOB_IMAGE_NAME}:latest']
timeout: 3600s
