# Istio
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: proxy-server
spec:
  hosts:
    - proxy-server
  http:
    - match:                            # `http.match` タグで、リクエスト送信先の振り分け条件を定義できる
        - headers:                      # リクエストヘッダー
            target:
              exact: condition1         # ヘッダーの値
      route:                            # `http.match.route` タグで、`match` タグで定義した振り分け条件に一致したときのリクエスト送信先を定義できる
        - destination:
            host: proxy-server
            subset: proxy-pod-subset1   # DestinationRule 定義ファイルの spec.subsets.name タグで定義した値
      timeout: 10s
    - route:                            # 最後に定義した `http.route` タグで、`match` タグで定義した振り分け条件に一致しない場合のリクエスト送信先を定義できる。
        - destination:
            host: proxy-server
            subset: proxy-pod-subset2
      timeout: 10s
