version: "3"

services:
  elixir-api-server:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ${PWD}:/api
    # 
    command: mix phx.server