version: "3"

services:
  elixir-phoenix-api-server:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ${PWD}:/api
    command: mix phx.server
