# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-ios-app-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-ios-app-project
  pod 'Firebase/Core'       # Firebase のコア部分のライブラリ
  #pod 'Firebase/Auth'       # Firebase Authentication のライブラリ

  target 'sample-ios-app-projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample-ios-app-projectUITests' do
    # Pods for testing
  end

end
