version: '2.3'

services:
  predict_server:
    container_name: predict-container
    image: predict-image
    build:
      context: "predict/"
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/predict:/predict
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5001:5001"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      BINARY_THRESHOLD: "250"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5001 -w 1 -k uvicorn.workers.UvicornWorker --reload"

  redis_server:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: bash -c "redis-server"

  proxy_server:
    container_name: proxy-container
    image: proxy-image
    build:
      context: "proxy/"
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/proxy:/proxy
      - ${PWD}/redis:/redis
      - ${PWD}/utils:/utils
      - ${PWD}/config:/config
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - predict_server
      - redis_server
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PREDICT_SERVER_URL: "http://predict-container:5001"
    command: bash -c "gunicorn app:app --bind 0.0.0.0:5000 -w 1 -k uvicorn.workers.UvicornWorker --reload"
