version: '2.3'

services:
  fast-api-server:
      container_name: fast-api-sentry-container
      image: fast-api-sentry-image
      build:
        context: "api/"
        dockerfile: Dockerfile
      volumes:
        - ${PWD}/api:/api
      ports:
        - "5001:5001"
      tty: true
      environment:
        TZ: "Asia/Tokyo"
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      command: bash -c "gunicorn app:app --bind 0.0.0.0:5001 -w 1 -k uvicorn.workers.UvicornWorker --reload"

