---
# Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-pod
  labels:
    app: predict-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict-pod
  template:
    metadata:
      labels:
        app: predict-pod
    spec:
      containers:
      - name: predict-container
        image: gcr.io/my-project2-303004/predict-image-gke:latest
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5001 --workers 1 --threads 1 --backlog 256 --reload"]
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: predict-server
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: predict-pod
---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: predict-auto-scale
  namespace: default
spec:
  scaleTargetRef:     # autoscale 対象となる `scaled resource object` を指定
    apiVersion: apps/v1
    kind: Deployment
    name: predict-pod
  minReplicas: 1      # 最小 Pod 数
  maxReplicas: 4      # 最大 Pod 数
  metrics:
  - type: External  # 外部メトリクス（kubernetesクラスタ内のリソースとは関係しないメトリクス）
    external:
      metricName: custom.googleapis.com|n_queues_in_redis   # Kubernetes API では指標名にスラッシュを使用できないため、パイプ記号（|）で置き換える必要がある
      targetValue: 0.5                                      # 1つのPodが処理すべき値を決め打ちで指定する。
