substitutions:
  _IMAGE_NAME: graph-cut-api-image-gke

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    id: docker build
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
      '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
      '-f', 'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: docker push
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']

images: ['gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']
timeout: 100000s
