version: '3'
services:
  terraform-aws-service:
    container_name: terraform-aws-container
    image: terraform-aws-image
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/:/terraform/aws
      - ${HOME}/.ssh/:/.ssh
      - ${HOME}/.kube/config:/.kube/config
      - ${PWD}/k8s:/k8s
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
#      AWS_ACCESS_KEY_ID: xxx           
#      AWS_SECRET_ACCESS_KEY: xxx
#      AWS_DEFAULT_REGION: us-west-2
    env_file:
      - aws_key.env
