{
 "title": "slurm-exporter-dashboard",
 "tags": [ "slurm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Slurm Jobs",
   "type": "table",
   "description": "All Slurm Jobs",
   "targets": [
    {
     "expr": "sum by (user,account,partition) (slurm_account_jobs_pending > 0 or slurm_partition_jobs_pending > 0 or slurm_user_jobs_pending > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_queue_running > 0 or slurm_queue_pending > 0 or slurm_queue_completed > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node States",
   "type": "timeseries",
   "description": "Node States",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "slurm_nodes_alloc", "legendFormat": "Allocated" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle" },
    { "expr": "slurm_nodes_down", "legendFormat": "Down" }
   ]
  },
  {
   "title": "Jobs by State",
   "type": "timeseries",
   "description": "Jobs by State",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "slurm_queue_running", "legendFormat": "Running" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending" },
    { "expr": "slurm_queue_suspended", "legendFormat": "Suspended" }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "description": "CPU Usage by Node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "slurm_node_cpu_alloc", "legendFormat": "Allocated - {{node}}" },
    { "expr": "slurm_node_cpu_idle", "legendFormat": "Idle - {{node}}" }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "timeseries",
   "description": "Memory Usage by Node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "slurm_node_mem_alloc", "legendFormat": "Allocated - {{node}}" },
    { "expr": "slurm_node_mem_total", "legendFormat": "Total - {{node}}" }
   ]
  }
 ]
}