apiVersion: apps/v1         # Deployment の API バージョン。kubectl api-resources | grep Deployment と kubectl api-versions  | grep apps で確認可能  
kind: Deployment            # デプロイメント定義ファイルであることを明示
metadata:
  name: fast-api-pod        # 識別名
spec:
  replicas: 3               # Pod の数
  selector:
    matchLabels:
      app: fast-api-pod          # template:metadata:labels:app と同じ値にする必要がある
  template:                      # Pod のテンプレート。このテンプレートをもとに ReplicaSet がレプリカ数の Pod を作成する
    metadata:
      labels:                    # Pod をクラスタ内で識別のするためのラベル。service.yml で Pod を識別するラベルとして使用される
        app: fast-api-pod        # 識別名。selector:matchLabels:app と同じ値にする必要がある
    spec:
      containers:                # Pod 内で動作させるコンテナ群の設定
      - name: fast-api-container                                     # コンテナ名
        image: gcr.io/my-project2-303004/fast-api-image-gke:latest     # Container Registry にアップロードした docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http-server
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker --reload"]
        resources:
          limits:
            cpu: 500m
            memory: "300Mi"
