# Service
apiVersion: v1
kind: Service
metadata:
  name: graph-cut-api-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: https
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: graph-cut-api-pod
    