version: '2.3'

services:
  sample-job-service:
    container_name: sample-job-container
    image: sample-job-image
    build:
      context: "job/"
      dockerfile: Dockerfile_dev
    volumes:
      - ${PWD}/job:/job
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: bash -c "python job.py"
