version: '3'
services:
  terraform-gcp-service:
    container_name: terraform-gcp-container
    image: terraform-gcp-image
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/terraform
      - ${HOME}/.config/gcloud/:/.config/gcloud   # ~/.config/gcloud/application_default_credentials.json を同期
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      GOOGLE_APPLICATION_CREDENTIALS: /.config/gcloud/application_default_credentials.json  # terraform で各種 GCP サービスを認識できるようにする
