name: Claude Code Reusable

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-reusable:
    uses: Yagami360/claude-code-custom-actions/.github/workflows/claude.yml@master
    with:
      # trigger_phrase: "@claude"
      trigger_phrase: "@claude-reusable"
      # assignee_trigger: "Yagami360"
      max_turns: 1
      system_prompt: |
        常に日本語で回答してください。
        コードレビューを行う際は、以下の点に注意してください：
        1. コーディング標準への準拠
        2. 新しいコードにはテストが含まれているか
        3. TypeScriptを新しいファイルで使用しているか
        4. セキュリティの観点からの問題はないか
        5. パフォーマンスの改善点
        簡潔で実用的なフィードバックを提供してください。
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
